# Generated by Django 6.0 on 2025-12-19 05:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('contenido', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('pais_nom', models.CharField(max_length=15)),
                ('moneda', models.CharField(max_length=3)),
                ('sis_de_imp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=25)),
                ('mail', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=128)),
                ('rol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id_contribuyente', models.AutoField(primary_key=True, serialize=False)),
                ('situación', models.CharField(max_length=20)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('actividad_economica', models.CharField(max_length=50)),
                ('identificador_tributario', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('empleados', models.IntegerField()),
                ('categoria', models.CharField(max_length=40)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.pais')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionTributaria',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_tributo', models.CharField(max_length=15)),
                ('monto', models.IntegerField()),
                ('codigo_CIIU', models.IntegerField()),
                ('regimen', models.TextField()),
                ('fecha_de_creacion', models.DateField()),
                ('id_contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.contribuyente')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.pais')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario')),
            ],
        ),
    ]
