# Generated by Django 5.1.3 on 2025-12-10 03:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0019_remove_clasificaciontributaria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
