# Generated by Django 6.0 on 2025-12-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0020_alter_evento_timestamp_alter_evento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mail',
            field=models.CharField(max_length=255),
        ),
    ]
